### ISSUE TITLE
Using Xray Id generator does not work

### ISSUE THREAD

**Issue by kushal-ti** [aws-observability/aws-otel-js#86]
I'm using the X-Ray Id generator in my tracing config, but the generated id are still not compatible with the X-Ray trace id spec, but instead they're just random strings as generated by open telemetry

This is my tracing.js file 

```javascript
const tracerConfig = {
  idGenerator: new AWSXRayIdGenerator(),
  instrumentations: [getNodeAutoInstrumentations()],
  resources: Resource.default().merge(
    new Resource({
      [SemanticResourceAttributes.SERVICE_NAME]: 'backend',
    }),
  ),
};

const provider = new NodeTracerProvider({ tracerConfig });

const exporter = new OTLPTraceExporter({
  url: `http://localhost:4318/v1/traces`,
});

provider.addSpanProcessor(new SimpleSpanProcessor(exporter));
provider.register({
  propagator: new AWSXRayPropagator(),
});

```

and this is the otel-config file for aws otel collector
```yaml
extensions:
  health_check:
  pprof:
    endpoint: 0.0.0.0:1777

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:

exporters:
  logging:
    loglevel: debug
  awsxray:
    region: "us-east-1"
  awsemf:
    region: "us-east-1"

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [awsxray, logging]
    metrics:
      receivers: [otlp]
      exporters: [awsemf]

  extensions: [pprof]
  telemetry:
    logs:
      level: debug
```

When i run the application, i get the following logs where trace id is just random string 
```bash
{"level":"INFO","logger":"root","message":"my log message","service.name":"backend","span_id":"3d5882bfbb0b3c80","timestamp":"2022-06-17T05:45:11.638Z","trace_flags":"01","trace_id":"26bbc3411267031fb55ebb03fcbcc4b7"}
```

And the following error message form the otel collector 
```bash
2022-06-17T05:48:53.201Z	debug	awsxrayexporter@v0.51.0/awsxray.go:99	Error translating span.	{"kind": "exporter", "name": "awsxray", "error": "invalid xray traceid: 26bbc3411267031fb55ebb03fcbcc4b7"}
```
